addSbtPlugin("com.47deg"          % "sbt-microsites"         % "1.2.1")
addSbtPlugin("org.tpolecat"       % "tut-plugin"             % "0.6.13")
addSbtPlugin("com.eed3si9n"       % "sbt-unidoc"             % "0.4.3")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"          % "0.9.0")
addSbtPlugin("com.github.gseitz"  % "sbt-release"            % "1.0.13")
addSbtPlugin("io.crashbox"        % "sbt-gpg"                % "0.2.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                % "0.3.7")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"          % "1.6.1")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"           % "3.9.3")

addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.1.1")
